# fly.toml app configuration file generated for wololo on 2024-10-18T18:48:22-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wololo'
primary_region = 'dfw'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = "/app/bin/wololo eval \"Code.eval_file(\\\"/app/rel/cron_job.exs\\\")\""

[processes]
  app = "/app/bin/server"
  cron = "supercronic /app/crontab"

[env]
  PHX_HOST = 'aoe4stats.com'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
